/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    trips: Trip;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  titlu: string;
  /**
   * Slug-ul este un identificator unic folosit în URL pentru a genera linkul final. Exemplu: https://tripviewer.vercel.app/trips/aurore, unde aurore e slug-ul.
   */
  slug: string;
  imagine: number | Media;
  zborDePlecare: {
    orasPlecare: string;
    orasSosire: string;
    areEscala?: boolean | null;
    zbor: {
      companieAeriana: string;
      numarZbor: string;
      aeroportPlecare: string;
      dataPlecare: string;
      aeroportSosire: string;
      dataSosire: string;
    };
    escala?: {
      aeroport?: string | null;
      durata?: string | null;
    };
    zbor2?: {
      companieAeriana: string;
      numarZbor: string;
      aeroportPlecare: string;
      dataPlecare: string;
      aeroportSosire: string;
      dataSosire: string;
    };
  };
  zborDeIntoarcere: {
    orasPlecare: string;
    orasSosire: string;
    areEscala?: boolean | null;
    zbor: {
      companieAeriana: string;
      numarZbor: string;
      aeroportPlecare: string;
      dataPlecare: string;
      aeroportSosire: string;
      dataSosire: string;
    };
    escala?: {
      aeroport?: string | null;
      durata?: string | null;
    };
    zbor2?: {
      companieAeriana: string;
      numarZbor: string;
      aeroportPlecare: string;
      dataPlecare: string;
      aeroportSosire: string;
      dataSosire: string;
    };
  };
  ghid: {
    nume: string;
    telefon: string;
    informatiiSuplimentare?: string | null;
  };
  informatiiSuplimentareExcursie?: {
    informatii?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  itinerariuZile?:
    | {
        titlu: string;
        activitati: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  imagine?: T;
  zborDePlecare?:
    | T
    | {
        orasPlecare?: T;
        orasSosire?: T;
        areEscala?: T;
        zbor?:
          | T
          | {
              companieAeriana?: T;
              numarZbor?: T;
              aeroportPlecare?: T;
              dataPlecare?: T;
              aeroportSosire?: T;
              dataSosire?: T;
            };
        escala?:
          | T
          | {
              aeroport?: T;
              durata?: T;
            };
        zbor2?:
          | T
          | {
              companieAeriana?: T;
              numarZbor?: T;
              aeroportPlecare?: T;
              dataPlecare?: T;
              aeroportSosire?: T;
              dataSosire?: T;
            };
      };
  zborDeIntoarcere?:
    | T
    | {
        orasPlecare?: T;
        orasSosire?: T;
        areEscala?: T;
        zbor?:
          | T
          | {
              companieAeriana?: T;
              numarZbor?: T;
              aeroportPlecare?: T;
              dataPlecare?: T;
              aeroportSosire?: T;
              dataSosire?: T;
            };
        escala?:
          | T
          | {
              aeroport?: T;
              durata?: T;
            };
        zbor2?:
          | T
          | {
              companieAeriana?: T;
              numarZbor?: T;
              aeroportPlecare?: T;
              dataPlecare?: T;
              aeroportSosire?: T;
              dataSosire?: T;
            };
      };
  ghid?:
    | T
    | {
        nume?: T;
        telefon?: T;
        informatiiSuplimentare?: T;
      };
  informatiiSuplimentareExcursie?:
    | T
    | {
        informatii?: T;
      };
  itinerariuZile?:
    | T
    | {
        titlu?: T;
        activitati?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}